---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./grafana.yaml
  - ./grafanadashboard.yaml
  - ./grafanadatasource.yaml
  - ./servicemonitor.yaml
configurations:
  - kustomizeconfig.yaml
configMapGenerator:
  - name: grafana-dashboard-home-energy
    files:
      - home-energy.json=./dashboards/home-energy.json
  - name: grafana-dashboard-home-energy-pro
    files:
      - home-energy-pro.json=./dashboards/home-energy-pro.json
  - name: grafana-dashboard-home-energy-roi
    files:
      - home-energy-roi.json=./dashboards/home-energy-roi.json
  - name: grafana-dashboard-home-energy-battery
    files:
      - home-energy-battery.json=./dashboards/home-energy-battery.json
  - name: grafana-dashboard-home-power-live
    files:
      - home-power-live.json=./dashboards/home-power-live.json
