---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app teslamate
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    controllers:
      teslamate:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.4.0@sha256:ebd9d30add17acdf935d73eb004758c7dfd9388aaa605fda70ad74378ab92aec
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: teslamate-secret
        containers:
          app:
            image:
              repository: mirror.gcr.io/teslamate/teslamate
              tag: 4.0.1@sha256:e77ec65007aafb40d736ed2c89675112fe8d960886ea9d7de3255f2b5360269f
            env:
              TZ: "${TZ}"
              DISABLE_MQTT: "false"
              MQTT_HOST: mosquitto.automation.svc.cluster.local
            envFrom:
              - secretRef:
                  name: teslamate-secret
            resources:
              requests:
                cpu: 18m
                memory: 338Mi
              limits:
                memory: 1024Mi
          agile:
            image:
              repository: ghcr.io/adampetrovic/teslamateagile
              tag: latest@sha256:8ad1f303b10b4cbf11bd08eccd641e4a9fec17d14ae55921132dfba81fe23eb9
            env:
              TeslaMate__UpdateIntervalSeconds: 300
              TeslaMate__GeofenceId: 4
              TeslaMate__EnergyProvider: HomeAssistant
              TeslaMate__LookbackDays: 7
              TeslaMate__Phases: 3
              Logging__LogLevel__Default: Debug
              Logging__Console__FormatterName: simple
              Logging__Console__FormatterOptions__TimestampFormat: "yyyy-MM-dd HH:mm:ss.fff"
              HomeAssistant__BaseUrl: http://home-assistant.automation.svc.cluster.local:8123
              HomeAssistant__EntityId: sensor.tesla_effective_price
            envFrom:
              - secretRef:
                  name: teslamate-secret
    service:
      app:
        controller: teslamate
        ports:
          http:
            port: 4000

    route:
      app:
        hostnames:
          - "teslamate.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
    postgresql:
      enabled: false
    resources:
      requests:
        cpu: 18m
        memory: 512Mi
      limits:
        memory: 512Mi
