router bgp 64513
 bgp router-id 10.0.87.1
 no bgp default ipv4-unicast

 neighbor K8S_CILIUM peer-group
 neighbor K8S_CILIUM remote-as 64514
 neighbor K8S_CILIUM description Cilium Kubernetes nodes

 neighbor 10.0.80.10 peer-group K8S_CILIUM
 neighbor 10.0.80.11 peer-group K8S_CILIUM
 neighbor 10.0.80.12 peer-group K8S_CILIUM
 neighbor 10.0.80.13 peer-group K8S_CILIUM
 neighbor 10.0.80.14 peer-group K8S_CILIUM

 address-family ipv4 unicast
  neighbor K8S_CILIUM activate
  neighbor K8S_CILIUM soft-reconfiguration inbound
  neighbor K8S_CILIUM route-map K8S_CILIUM_IN in
  neighbor K8S_CILIUM route-map K8S_CILIUM_OUT out
  neighbor K8S_CILIUM maximum-prefix 3
  maximum-paths 5
 exit-address-family
exit

route-map K8S_CILIUM_IN permit 10
 match ip address prefix-list K8S_CILIUM_VIPS
exit

route-map K8S_CILIUM_IN deny 100
exit

route-map K8S_CILIUM_OUT deny 100
exit

ip prefix-list K8S_CILIUM_VIPS seq 10 permit 10.0.88.200/32
ip prefix-list K8S_CILIUM_VIPS seq 20 permit 10.0.88.201/32
ip prefix-list K8S_CILIUM_VIPS seq 30 permit 10.0.88.10/32
