---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app camera-view
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      camera-view:
        containers:
          app:
            image:
              repository: ghcr.io/adampetrovic/camera-view
              tag: latest@sha256:e591d3d666ece720a734c82011bb7d42232ba9b43d48a0160bc7c14a4cb0e813
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 5m
                memory: 16Mi
              limits:
                memory: 64Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
    service:
      app:
        ports:
          http:
            port: *port
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
      run:
        type: emptyDir
        globalMounts:
          - path: /var/run
