apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:b4+jbTux6OtFbSwKIQ9SXw==,iv:J7eTq/c2fKuCQ3mgvfBSrfvtrY5F24eMBXNkH3vHkM4=,tag:6fmt6z69SRDfzP6yCo1IFQ==,type:str]
    SECRET_PUBLIC_DOMAIN: ENC[AES256_GCM,data:rDh2EnXNPtkHcSNttU0=,iv:k1VPKlxwC498O2n7qkFyspn23SG62QwJKlIPB7OrfMY=,tag:P/cv4DdqEKFz0a9saGKuLQ==,type:str]
    SECRET_PUBLIC_ANON_DOMAIN: ENC[AES256_GCM,data:bbCLQ0z+t3tdXoRq,iv:+GmiYdm260xFptKxw8d8GDEZDWagKHBNmuOG3getbTI=,tag:vFql7qUksew3oFyw148amQ==,type:str]
    SECRET_PLEX_DOMAIN: ENC[AES256_GCM,data:rIwNpnfZguqdH4UH,iv:yGdKx5O/K/rVlWISMpENwbnjq1FaWj+U2u9XlGMDT9A=,tag:zZxb8PlUnZ6nGhZY7I0U4w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:a97SDTDH/TW9f1Pno3BsNbLeRt0=,iv:pB4ogbGxdcbb8XpORwJQzVC1ijhDSAlZV30oBBQfvHA=,tag:zXL0TX0LzgYzgGH2GRq0yg==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:RrGVXBSgzX7n1FEjLiIklTlxTHoiOUtSZnPEZoN6APQ=,iv:oZSHlzbXiE/fVVeVqlFc2IMej8JEc+ehC6EuQyM4qdQ=,tag:QnT4MfHow6C49TlzswDq5A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:cmrIgug1qMj2jBlqA1iijgCbwSh48E7FzkIuelLQbPwJ/8NF,iv:otPMVM7yPvZmrLg3v0fCzDolCrLjIyFEZUy4uU2rndY=,tag:K8iD6oPSIy4a+BaLSdw38w==,type:str]
    SECRET_NFS_DOMAIN: ENC[AES256_GCM,data:sFJpyGzQMqRoNzqTeK7WhJ9TyYCIi1HzpReVeQ==,iv:l+ky5TLDeVrKv7sd1c8cBa7yC2zJPuo2WeNIA4C5BTc=,tag:A2g1/YMLd0DoE9aR+fSgBA==,type:str]
    SECRET_SIGENERGY_IP: ENC[AES256_GCM,data:btA4jgOddu9zmw==,iv:N1LXn1TOEXiIqLQhVVtHSfdm0RNnwGqUlpN/mw69Qng=,tag:e9kelMvWEo4neA4ABpBQUA==,type:str]
    TZ: ENC[AES256_GCM,data:WE0+y+BvfM1feLWrqXXkGA==,iv:sAiBEf2XlqPNE5irq7/vKCbiwRqezIq0+8W08z3sLJw=,tag:CnnZTl+3Ry/x7Mhfne7tqg==,type:str]
# noinspection KubernetesUnknownKeys
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFb0FKbWZva1BPZTNBZS93
            L09hNWU5TWFFWEV1NkkvZ2R6OS9Nanp4TGtZCkhCKy9FKytoSTE2UEFLaS84cDRw
            ZldyQXZFUDNsRHIzdFU1a204QmFhNmsKLS0tIG9yN01xWTBPc0Z6V2RPUnVPdC84
            Z1FvYjVhYnFnY3V0Y3NDbmpsaHZjOTgKAdPthVGTjniTw4pmiGPnHrbJ376UrxBj
            4BB9t5POvirLSsszEUTlZ44zKeOzSACmbqYqphyaO/Znpnb3Z5JKug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pvlc4c05yg9g0pst6f6uvthh7942vt5tx79ycva92y8matj2ne5qvz4md5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T04:14:58Z"
    mac: ENC[AES256_GCM,data:XJWeoS0YoZQrNxdh2VJpQ5qgJ3LChJbBkhXw2BTmm9CRCBM9i56TbbxUPXXtIQYKHl4EDRsE++EmFMg5F+Fz05fkKQ5YZc5cjhCJrT0aMOmM4H80/jneuHJORw5CDuTSf0PFH9K3sRTK8yanTxgEmHrzNy2MVxgd1x/Vj5v7NTA=,iv:Ip/wvrJ9qZYmIPa8Ri/JiL3G4ystq6KaewbBt/nR97k=,tag:2i3sTkHHBCT2opWaaYqILA==,type:str]
    version: 3.11.0
