# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tdarr
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [44, 100]

    controllers:
      tdarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr
              tag: 2.70.01@sha256:4d48a46fb984b29e07cf4fd66cf7d3c8bd7c2c8dd662d09b4e20e11ae93e52fc
            env:
              TZ: "${TZ}"
              PUID: "568"
              PGID: "568"
              UMASK_SET: "002"
              inContainer: "true"
              ffmpegVersion: "7"
              maxLogSizeMB: "10"
              cronPluginUpdate: ""
              serverIP: "0.0.0.0"
              serverPort: &serverPort 8266
              webUIPort: &webPort 8265
              internalNode: "false"
              auth: "false"
              openBrowser: "false"
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 3Gi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *webPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *webPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 30

      tdarr-node:
        type: daemonset
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/haveagitgat/tdarr_node
              tag: 2.70.01@sha256:60176a6ffc7584edde5420b7e1816f60227aa166f159b58a721d34564075c6e4
            env:
              TZ: "${TZ}"
              PUID: "568"
              PGID: "568"
              UMASK_SET: "002"
              inContainer: "true"
              ffmpegVersion: "7"
              maxLogSizeMB: "10"
              cronPluginUpdate: ""
              nodeName:
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: spec.nodeName
              serverIP: tdarr.media.svc.cluster.local
              serverPort: *serverPort
              nodeType: mapped
              priority: "-1"
              apiKey: ""
              pollInterval: "2000"
              startPaused: "false"
              transcodegpuWorkers: "1"
              transcodecpuWorkers: "0"
              healthcheckgpuWorkers: "0"
              healthcheckcpuWorkers: "1"
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: node-role.kubernetes.io/control-plane
                        operator: DoesNotExist

    service:
      app:
        controller: tdarr
        ports:
          http:
            port: *webPort
          server:
            port: *serverPort

    route:
      app:
        hostnames:
          - tdarr.${SECRET_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: http

    persistence:
      config:
        enabled: true
        existingClaim: tdarr
        advancedMounts:
          tdarr:
            app:
              - path: /app/server
                subPath: server
              - path: /app/configs
                subPath: configs
              - path: /app/logs
                subPath: logs
      node-config:
        type: emptyDir
        advancedMounts:
          tdarr-node:
            app:
              - path: /app/configs
      node-logs:
        type: emptyDir
        advancedMounts:
          tdarr-node:
            app:
              - path: /app/logs
      cache:
        type: nfs
        server: ${SECRET_NFS_DOMAIN}
        path: /volume2/downloads
        globalMounts:
          - path: /temp
            subPath: tdarr-cache
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      movies:
        type: nfs
        server: ${SECRET_NFS_DOMAIN}
        path: /volume2/movies
        globalMounts:
          - path: /movies
            readOnly: false
      movies-kids:
        type: nfs
        server: ${SECRET_NFS_DOMAIN}
        path: /volume2/kids/movies
        globalMounts:
          - path: /movies-kids
            readOnly: false
      tv:
        type: nfs
        server: ${SECRET_NFS_DOMAIN}
        path: /volume2/tv
        globalMounts:
          - path: /tv
            readOnly: false
      tv-kids:
        type: nfs
        server: ${SECRET_NFS_DOMAIN}
        path: /volume2/kids/tv
        globalMounts:
          - path: /tv-kids
            readOnly: false
