---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}-r2
spec:
  repository:
    kind: ClusterRepository
    name: kopiur-r2
  sources:
    - pvc:
        name: ${APP}
      readOnly: true
  copyMethod: Snapshot
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
  compression:
    compressor: zstd
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  mover:
    cache:
      mode: Persistent
      capacity: ${KOPIUR_CAPACITY:=5Gi}
      storageClassName: ${KOPIUR_CACHE_STORAGECLASS:-ceph-block}
    securityContext:
      runAsUser: ${KOPIUR_PUID:-568}
      runAsGroup: ${KOPIUR_PGID:-568}
---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}-nfs
spec:
  repository:
    kind: ClusterRepository
    name: kopiur-nfs
  sources:
    - pvc:
        name: ${APP}
      readOnly: true
  copyMethod: Snapshot
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
  compression:
    compressor: zstd
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
  mover:
    cache:
      mode: Persistent
      capacity: ${KOPIUR_CAPACITY:=5Gi}
      storageClassName: ${KOPIUR_CACHE_STORAGECLASS:-ceph-block}
    securityContext:
      runAsUser: ${KOPIUR_PUID:-568}
      runAsGroup: ${KOPIUR_PGID:-568}
