---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  repository:
    kind: ClusterRepository
    name: ${KOPIUR_REPOSITORY:-kopiur-r2}
  sources:
    - pvc:
        name: ${APP}
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
  compression:
    compressor: zstd
  retention:
    keepLatest: 3
    keepHourly: 24
    keepDaily: 7
    keepWeekly: 4
    keepMonthly: 1
  mover:
    cache:
      mode: Persistent
      capacity: ${KOPIUR_CACHE_CAPACITY:-2Gi}
      storageClassName: ${KOPIUR_CACHE_STORAGECLASS:-ceph-block}
    securityContext:
      runAsUser: ${KOPIUR_PUID:-568}
      runAsGroup: ${KOPIUR_PGID:-568}
