[env]
SOPS_AGE_KEY_FILE = "/Users/adam/.config/sops/age/keys.txt"

[tools]
# Kubernetes
kubectl = "1.35.1"
helm = "4.1.1"
helmfile = "1.2.3"
kustomize = "5.8.1"
flux2 = "2.7.5"

# Talos
talosctl = "1.13.0"
talhelper = "3.1.10"

# Secrets
sops = "3.11.0"
age = "1.3.1"
1password-cli = "2.32.1"

# Utilities
jq = "1.8.1"
yq = "4.52.2"
task = "3.48.0"
fzf = "0.67.0"
gh = "2.86.0"
