---
originRequest:
  originServerName: "external.${SECRET_PUBLIC_DOMAIN}"

ingress:
  - hostname: "${SECRET_PUBLIC_DOMAIN}"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.${SECRET_PUBLIC_DOMAIN}"
    service: *svc
  - hostname: "${SECRET_PLEX_DOMAIN}"
    service: *svc
  - hostname: "*.${SECRET_PLEX_DOMAIN}"
    service: *svc
  - service: http_status:404
