---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: smtp-relay
spec:
  secretName: tls.smtp-relay
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: smtp.petrovic.network
  dnsNames:
    - smtp.petrovic.network
  privateKey:
    rotationPolicy: Always

