---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: ${job}
  namespace: ${ns}
spec:
  trigger:
    manual: restore-once
  kopia:
    repository: ${app}-volsync-secret
    destinationPVC: ${claim}
    copyMethod: Direct
    sourceIdentity:
      sourceName: ${app}
    moverSecurityContext:
      runAsUser: ${puid}
      runAsGroup: ${pgid}
      fsGroup: ${pgid}
