#file: noinspection KubernetesUnknownValues
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${APP}"
  labels:
    kustomize.toolkit.fluxcd.io/ssa: IfNotPresent
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: ["${KOPIUR_ACCESSMODES:-ReadWriteOnce}"]
  resources:
    requests:
      storage: "${KOPIUR_CAPACITY}"
  storageClassName: "${KOPIUR_STORAGECLASS:-ceph-block}"
