---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gdb-web-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:18.3-3.6.2-standard-bookworm@sha256:0b107a47d516d63e52257810a01befc7fc8d72e17a08ede6e72a277461e11ef0
  primaryUpdateStrategy: unsupervised
  storage:
    size: 40Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: gdb
      owner: gdb
      secret:
        name: gdb-db-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis
        - CREATE EXTENSION IF NOT EXISTS pg_trgm
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &backup
        barmanObjectName: gdb-web-garage
        serverName: gdb-web-postgres
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *backup
