---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-postgres-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-postgres-app-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: gdb
        password: "{{ .POSTGRES_PASS }}"
  data:
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: gdb
        property: POSTGRES_PASS
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-runtime
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-runtime-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://gdb:{{ .POSTGRES_PASS }}@gdb-postgres-rw.gdb.svc.cluster.local:5432/gdb?sslmode=disable"
  data:
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: gdb
        property: POSTGRES_PASS
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-postgres-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-postgres-superuser-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: cloudnative-pg
        property: POSTGRES_SUPER_PASS
    - secretKey: aws-access-key-id
      remoteRef:
        key: cloudnative-pg
        property: AWS_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: cloudnative-pg
        property: AWS_SECRET_ACCESS_KEY
