---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-internal
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-secret
    template:
      data:
        CF_API_TOKEN: "{{ .CLOUDFLARE_API_TOKEN }}"
        CF_PUBLIC_ZONE_ID: "{{ .CLOUDFLARE_PUBLIC_ZONE_ID }}"
        CF_PLEXOVIC_ZONE_ID: "{{ .CLOUDFLARE_PLEXOVIC_ZONE_ID }}"
  dataFrom:
    - extract:
        key: cloudflare-dns
