---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-scraper-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-scraper-proxy-secret
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_PROXY_URL
      remoteRef:
        key: gdb
        property: EXTERNAL_PROXY_URL
