---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sigenergy2mqtt
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sigenergy2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # MQTT credentials
        SIGENERGY2MQTT_MQTT_USERNAME: "{{ .MQTT_USERNAME }}"
        SIGENERGY2MQTT_MQTT_PASSWORD: "{{ .MQTT_PASSWORD }}"

        # InfluxDB v2 credentials
        SIGENERGY2MQTT_INFLUX_TOKEN: "{{ .SIGENERGY2MQTT_INFLUX_TOKEN }}"
        SIGENERGY2MQTT_INFLUX_ORG: "{{ .SIGENERGY2MQTT_INFLUX_ORGANIZATION }}"

  dataFrom:
    - extract:
        key: mosquitto
      rewrite:
        - regexp:
            source: "(.*)"
            target: "MQTT_$1"
    - extract:
        key: sigenergy2mqtt
