---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bookorbit-postgres
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17.8-1.1.0@sha256:1bb77658b6ee347554e36a5d34f064e155f0bc39c16c3fd8a50fc3041c319e2f
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: ceph-block
  enableSuperuserAccess: true
  superuserSecret:
    name: bookorbit-db-superuser-secret
  bootstrap:
    initdb:
      database: bookorbit
      owner: bookorbit
      secret:
        name: bookorbit-db-secret
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp"
        - CREATE EXTENSION IF NOT EXISTS pg_trgm
        - CREATE EXTENSION IF NOT EXISTS unaccent
        - CREATE EXTENSION IF NOT EXISTS vector
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: 256MB
  enablePDB: false
  resources:
    requests:
      cpu: 100m
      memory: 768Mi
    limits:
      memory: 2Gi
  monitoring:
    enablePodMonitor: true
    podMonitorMetricRelabelings:
      - sourceLabels: ["cluster"]
        targetLabel: cnpg_cluster
        action: replace
      - regex: cluster
        action: labeldrop
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters: &parameters
        barmanObjectName: bookorbit-garage
        serverName: bookorbit-postgres
  externalClusters:
    - name: source
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters: *parameters
