---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dawarich-secret
    template:
      data:
        # Postgres Init
        INIT_POSTGRES_DBNAME: dawarich
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local.
        INIT_POSTGRES_USER: "{{ .DAWARICH_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .DAWARICH_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
        DATABASE_HOST: postgres-rw.database.svc.cluster.local.
        DATABASE_PORT: "5432"
        DATABASE_USERNAME: "{{ .DAWARICH_POSTGRES_USER }}"
        DATABASE_PASSWORD: "{{ .DAWARICH_POSTGRES_PASS }}"
        DATABASE_NAME: dawarich
        SECRET_KEY_BASE: "{{ .DAWARICH_SECRET_KEY_BASE }}"
        OIDC_CLIENT_SECRET: "{{ .DAWARICH_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: dawarich
      rewrite:
        - regexp:
            source: "(.*)"
            target: "DAWARICH_$1"
    - extract:
        key: cloudnative-pg
    - extract:
        key: authelia
