---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tuppr.home-operations.com/kubernetesupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: v1.37.0
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        !has(status.phase) || !(status.phase in ["Pending", "Running", "Deleting"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: |-
        !has(status.phase) || !(status.phase in ["Pending", "Resolving", "Restoring"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: SnapshotReplication
      expr: |-
        !has(status.phase) || !(status.phase in ["Pending", "Replicating"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: RepositoryReplication
      expr: |-
        !has(status.phase) || !(status.phase in ["Pending", "Replicating"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Maintenance
      expr: |-
        !has(status.manualRun) || !has(status.manualRun.phase) || status.manualRun.phase != "Running"
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
