---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: TalosUpgrade
metadata:
  name: talos
spec:
  talos:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/talos
    version: v1.14.1
  parallelism: 1
  policy:
    rebootMode: powercycle
    waitForVolumeDetach: true
  healthChecks:
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Snapshot
      expr: |-
        !has(status.phase) || !(status.phase in ["Pending", "Running", "Deleting"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Restore
      expr: |-
        !has(status.phase) || !(status.phase in ["Resolving", "Restoring"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: SnapshotReplication
      expr: |-
        !has(status.phase) || !(status.phase in ["Pending", "Replicating"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: RepositoryReplication
      expr: |-
        !has(status.phase) || !(status.phase in ["Pending", "Replicating"])
    - apiVersion: kopiur.home-operations.com/v1alpha1
      kind: Maintenance
      expr: |-
        !has(status.manualRun) || !has(status.manualRun.phase) || status.manualRun.phase != "Running"
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      expr: |-
        status.ceph.health in ['HEALTH_OK']
