---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    controllers:
      changedetection:
        containers:
          app:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: "0.55.7@sha256:736331d2787f94d3201b64aa641e090f67e28577ba505bd7ba5d7c1841e1e0ca"
            env:
              TZ: "${TZ}"
              PORT: &port 5000
              USE_X_SETTINGS: 1
              BASE_URL: &host changedetection.${SECRET_DOMAIN}
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/chromium?stealth=1&--disable-web-security=true
          browser:
            image:
              repository: ghcr.io/browserless/chromium
              tag: v2.51.0@sha256:fee73de217759eb4053358dc09818b9e9a6cf4a1d1269a0d2da487e0797e0a22
            env:
              - {name: SCREEN_WIDTH, value: "1920"}
              - {name: SCREEN_HEIGHT, value: "1024"}
              - {name: SCREEN_DEPTH, value: "16"}
              - {name: ENABLE_DEBUGGER, value: "false"}
              - {name: TIMEOUT, value: "300000"}
              - {name: CONCURRENT, value: "5"}
            resources:
              requests:
                cpu: 100m
                memory: 768Mi
              limits:
                memory: 3Gi
    service:
      app:
        controller: changedetection
        ports:
          http:
            port: *port
    route:
      main:
        hostnames:
          - *host
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: changedetection
        advancedMounts:
          changedetection:
            app:
              - path: /datastore
