---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-backup-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-backup-secret
    creationPolicy: Owner
  data:
    - secretKey: aws-access-key-id
      remoteRef:
        key: cloudnative-pg
        property: AWS_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: cloudnative-pg
        property: AWS_SECRET_ACCESS_KEY
