---
# yaml-language-server: $schema=https://homelab-schemas-epg.pages.dev/postgresql.cnpg.io/backup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: gdb-postgres-pre-jobs-20261003
spec:
  cluster:
    name: gdb-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
