---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: gdb
        password: "{{ .password }}"
        DB_HOST: gdb-postgres-rw.gdb.svc.cluster.local
        DB_PORT: "5432"
        DB_USER: gdb
        DB_PASSWORD: "{{ .password }}"
        DB_NAME: gdb
        DB_SSL_MODE: disable
        DATABASE_URL: 'postgresql://gdb:{{ .password | urlquery | replace "+" "%20" }}@gdb-postgres-rw.gdb.svc.cluster.local:5432/gdb?sslmode=disable'
        EXTERNAL_PROXY_URL: "{{ .externalProxyUrl }}"
  data:
    - secretKey: password
      remoteRef:
        key: gdb
        property: POSTGRES_PASS
    - secretKey: externalProxyUrl
      remoteRef:
        key: gdb
        property: EXTERNAL_PROXY_URL
