---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-database-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: gdb
        password: "{{ .POSTGRES_PASS }}"
        aws-access-key-id: "{{ .AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: POSTGRES_PASS
      remoteRef:
        key: gdb
        property: POSTGRES_PASS
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: cloudnative-pg
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: cloudnative-pg
        property: AWS_SECRET_ACCESS_KEY
