---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./backup-secret.yaml
  - ./objectstore.yaml
  - ./cluster.yaml
  - ./scheduledbackup.yaml
  - ./backup-pre-jobs.yaml
