---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: energize
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: energize-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INFLUXDB_URL: "{{ .INFLUXDB_URL }}"
        INFLUXDB_ORG: "{{ .INFLUXDB_ORG }}"
        INFLUXDB_TOKEN: "{{ .INFLUXDB_TOKEN }}"
        INFLUXDB_BUCKET: "{{ .INFLUXDB_BUCKET }}"
  dataFrom:
    - extract:
        key: energize
