---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dispatcharr-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DB: dispatcharr
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASS }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: dispatcharr
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: dispatcharr
    - extract:
        key: cloudnative-pg
