---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pi-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pi-agent-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PI_AUTH_JSON: "{{ .PI_AUTH_JSON }}"
  dataFrom:
    - extract:
        key: pi-agent
