---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./actual-budget/ks.yaml
  - ./atuin/ks.yaml
  - ./babybuddy/ks.yaml
  - ./element-web/ks.yaml
  - ./filebrowser/ks.yaml
  - ./hister/ks.yaml
  - ./homebox/ks.yaml
  - ./memos/ks.yaml
  - ./miniflux/ks.yaml
  - ./paperless-ngx/ks.yaml
  - ./readeck/ks.yaml
  - ./synapse/ks.yaml
