---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./actual-budget/ks.yaml
  - ./atuin/ks.yaml
  - ./babybuddy/ks.yaml
  - ./energize/ks.yaml
  - ./filebrowser/ks.yaml
  - ./koffan/ks.yaml
  - ./memos/ks.yaml
  - ./miniflux/ks.yaml
  - ./paperless-ngx/ks.yaml
