---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gdb-db-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gdb-db-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: gdb
        password: "{{ .password }}"
        GDB_DATABASE_URL: 'postgresql+psycopg://gdb:{{ .password | urlquery | replace "+" "%20" }}@gdb-postgres-rw.default.svc.cluster.local:5432/gdb'
  data:
    - secretKey: password
      remoteRef:
        key: gdb
        property: POSTGRES_PASS
