---
apiVersion: v1
kind: Service
metadata:
  name: gdb-postgres
  annotations:
    external-dns.alpha.kubernetes.io/hostname: gdb-postgres.${SECRET_DOMAIN}
    lbipam.cilium.io/ips: 10.0.88.15
spec:
  type: LoadBalancer
  ports:
    - name: gdb-postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: gdb-postgres
    role: primary
