# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app webhook-bridge
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
  maxHistory: 3
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    controllers:
      webhook-bridge:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/adampetrovic/webhook-bridge
              tag: 0.1.0@sha256:baada7757302353ebb7c84c1f868584b672402dff2d73d38c65880de9452207c
            env:
              PORT: &port 8080
              AUTH_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: webhook-bridge-secret
                    key: AUTH_TOKEN
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
              seccompProfile:
                type: RuntimeDefault
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 64Mi
        pod:
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
    service:
      app:
        controller: webhook-bridge
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "webhook-bridge.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: http
