---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: element-web-assets
    files:
      - resources/config.json
      - resources/welcome.html
      - resources/welcome-bg.svg
      - resources/logo.svg
      - resources/custom.css
      - resources/default.conf.template
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/name: element-web
