---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./scanner-externalsecret.yaml
  - ./scanner-networkpolicy.yaml
components:
  - ../../../../components/authelia-proxy
configMapGenerator:
  - name: paperless-samba-config
    files:
      - config.yml=./resources/samba.yaml
  - name: paperless-post-consume
    files:
      - ./resources/post_consume.py
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
