---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kubetail
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kubetail
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    kubetail:
      dashboard:
        enabled: true
        authMode: auto
        image:
          registry: ghcr.io
          repository: kubetail-org/kubetail-dashboard
          tag: "0.17.0"
          digest: sha256:d1b0a9a6aaef33b7593d84b2c0a5eb92a2877fd9bd9dfaaf8baa190d746ea0ed
        container:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
            runAsGroup: 1000
        runtimeConfig:
          csrf:
            enabled: false
          session:
            cookie:
              secure: true
        service:
          ports:
            http: 8080

      clusterAPI:
        enabled: true
        image:
          registry: ghcr.io
          repository: kubetail-org/kubetail-cluster-api
          tag: "0.8.2"
          digest: sha256:c61d0b75f42a9f28fb847e48f8dc314ea318c6f9891a86d67fec93573c9b9705
        container:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            runAsUser: 1000
            runAsGroup: 1000

      clusterAgent:
        enabled: true
        image:
          registry: ghcr.io
          repository: kubetail-org/kubetail-cluster-agent
          tag: "0.7.1"
          digest: sha256:45bfb342be220c84dd844b6a633bb42defac408e902693b4729eda2bd658b0b4
        container:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              add:
                - DAC_READ_SEARCH
              drop:
                - ALL
            runAsUser: 1000
            runAsGroup: 1000
        podTemplate:
          securityContext:
            fsGroup: 0
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
