# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: marginalia
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: marginalia-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MARGINALIA_API_TOKEN: "{{ .MARGINALIA_API_TOKEN }}"
        MARGINALIA_READECK_TOKEN: "{{ .MARGINALIA_READECK_TOKEN }}"
  dataFrom:
    - extract:
        key: marginalia
