---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: batterywise-src
    files:
      - comparison.go=./src/comparison.go
      - eme.go=./src/eme.go
      - go.mod=./src/go.mod
      - go.sum=./src/go.sum
      - influx.go=./src/influx.go
      - main.go=./src/main.go
      - simulation.go=./src/simulation.go
      - store.go=./src/store.go
  - name: batterywise-web
    files:
      - app.js=./src/web/app.js
      - index.html=./src/web/index.html
      - styles.css=./src/web/styles.css
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
