---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tracearr-secret
    template:
      data:
        JWT_SECRET: "{{ .TRACEARR_JWT_SECRET }}"
        COOKIE_SECRET: "{{ .TRACEARR_COOKIE_SECRET }}"
        DATABASE_URL: "postgres://{{ .TRACEARR_POSTGRES_USER }}:{{ .TRACEARR_POSTGRES_PASS }}@tracearr-postgres-rw.media.svc.cluster.local:5432/tracearr"
  dataFrom:
    - extract:
        key: tracearr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "TRACEARR_$1"
