---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard
spec:
  secretName: tls-adguard
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dns.petrovic.network
  dnsNames:
    - dns.petrovic.network
    - adguard.petrovic.network
  privateKey:
    rotationPolicy: Always
