---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: adguard-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: adguard-sync-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ORIGIN_USERNAME: "{{ .ADGUARD_USERNAME }}"
        ORIGIN_PASSWORD: "{{ .ADGUARD_PASSWORD }}"
        REPLICA1_USERNAME: "{{ .ADGUARD_USERNAME }}"
        REPLICA1_PASSWORD: "{{ .ADGUARD_PASSWORD }}"
  data:
    - secretKey: ADGUARD_USERNAME
      remoteRef:
        key: adguard
        property: username
    - secretKey: ADGUARD_PASSWORD
      remoteRef:
        key: adguard
        property: password
