---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: automation
components:
  - ../../components/common
resources:
  - ./changedetection/ks.yaml
  - ./esphome/ks.yaml
  - ./evcc/ks.yaml
  - ./fernwood-booker/ks.yaml
  - ./frigate/ks.yaml
  - ./go2rtc/ks.yaml
  - ./home-assistant/ks.yaml
  - ./mosquitto/ks.yaml
  - ./nas-crypt/ks.yaml
  # - ./sigenergy2mqtt/ks.yaml  # TODO: enable after hardware install + set Modbus IP
  - ./teslamate/ks.yaml
  - ./zigbee2mqtt/ks.yaml
