---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-dns
spec:
  endpoints:
    - dnsName: "iota.petrovic.network"
      recordType: A
      targets: ["10.0.22.9"]
    - dnsName: "nas-direct.petrovic.network"
      recordType: A
      targets: ["10.0.10.3"]
    - dnsName: "unas-direct.petrovic.network"
      recordType: A
      targets: ["10.0.10.95"]
    - dnsName: "nvr-direct.petrovic.network"
      recordType: A
      targets: ["10.0.50.2"]
