---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: internal-dns
spec:
  endpoints:
    - dnsName: "iota.${SECRET_DOMAIN}"
      recordType: A
      targets: ["10.0.22.9"]
    - dnsName: "nas-direct.${SECRET_DOMAIN}"
      recordType: A
      targets: ["10.0.10.3"]
    - dnsName: "nvr-direct.${SECRET_DOMAIN}"
      recordType: A
      targets: ["10.0.50.2"]
