---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi-internal-dns
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: external-dns
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.8.2
        env:
          - name: UNIFI_HOST
            value: "https://10.0.0.1"
          - name: UNIFI_EXTERNAL_CONTROLLER
            value: "false"
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: unifi-dns-secret
                key: api-key
          - name: LOG_LEVEL
            value: info
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --gateway-name=envoy-internal
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
    policy: sync
    sources: ["gateway-httproute", "service"]
    txtPrefix: k8s.
    txtOwnerId: kubernetes-home-unifi
    domainFilters:
      - "${SECRET_DOMAIN}"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: unifi-dns-secret
