---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerr
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
