---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bookorbit-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgres://bookorbit:{{ .DB_PASSWORD | urlquery }}@bookorbit-postgres-rw.media.svc.cluster.local/bookorbit"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .SETUP_BOOTSTRAP_TOKEN }}"
        MIGRATION_ENCRYPTION_KEY: "{{ .MIGRATION_ENCRYPTION_KEY }}"
  dataFrom:
    - extract:
        key: bookorbit
