---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: volsync
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: volsync
    image: &image
      repository: ghcr.io/adampetrovic/volsync
      tag: v0.17.11-nolock.2@sha256:775a2aacfaa165454ce12b544961a0434291ba311a194b3cd967405f692aef5e
    kopia: *image
    rclone: *image
    restic: *image
    rsync: *image
    rsync-tls: *image
    syncthing: *image
    manageCRDs: true
    replicaCount: 1
    metrics:
      disableAuth: true
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 568
      runAsGroup: 568
